### PR TITLE
MAP 142 - Generated new .so file using usdot-asn1c compiler

### PR DESCRIPTION
**Pull request by DokurOmkar**
# PR Details
## Description
In this PR:
- Used [usdot-asn1c](https://github.com/usdot-fhwa-stol/usdot-asn1c) to generate header and source files for J2735 for the 2016 version
- Compared both .so files and generated files to see if there is a difference 
- Ran all the test cases to make sure newly generated .so file works with usdot-asn1c compiler
- Generated header and source files for J2945/A using usdot-asn1c compiler locally

## Related Jira Key
[MAP-142](https://usdot-carma.atlassian.net/browse/MAP-142)

## Motivation and Context
Till date, we have been using vlm/asn1c compiler to generate the header and source files for the J2735_2016.asn file. But, this compiler is not supporting the latest .asn files (J2945/A 2024 version). For this reason, we used usdot-asn1c compiler to generate the header and source files for J2945/A 2024 version.

Also, usdot-asn1c is used to validate if the new .so file generated using this compiler works with the existing JNI wrapper. This has been carried over as part of this story and hence the newly .so file committed.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

[MAP-142]: https://usdot-carma.atlassian.net/browse/MAP-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by saina-ramyar** [comment]
Please link the usdot asn1c library that you used

**Comment by saina-ramyar** [comment]
Also please confirm if this is still the 2016 standard?

**Comment by DokurOmkar** [comment]
> Also please confirm if this is still the 2016 standard?

Updated the description with J2735 version.

**Comment by DokurOmkar** [comment]
> Please link the usdot asn1c library that you used

Updated the description of the PR to reflect the usdot-asn1c compiler link.

**Review by saina-ramyar — APPROVED** [review]

**Pull request merged**
